### ISSUE TITLE
[ BUG ]  php/login.php line:7 

### ISSUE THREAD

**Issue by WilderMO** [WilderMO/Web-CAD#14]
**Describe the bug**
PHP Error. 
Cant find Sysntax.

**To Reproduce**
1. Go on page
2. login
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/66009198/155749217-473f06ad-039d-41ea-8d30-8464c93a3b35.png)

**Comment by leonardsangoroh** [comment]
If you don't mind, kindly assign this issue to me and I'll work on it

**Comment by WilderMO** [comment]
Thanks

**Comment by leonardsangoroh** [comment]
<?php
  session_start();
  include "connect.php";

?>

In the index.php file you have started the session before connecting to the database, could this be causing the error?

@WilderMO I think you should connect to the database first before starting the session

I have also noticed that all the forms lack the "action" attribute which should link the next file to be run when the action, in this case clicking the button, is executed
